// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProxyImage(arg1) {
  return window['go']['services']['ProxyService']['ProxyImage'](arg1);
}
