// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSetting'](arg1, arg2, arg3);
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetCurrentUser(arg1) {
  return window['go']['main']['App']['GetCurrentUser'](arg1);
}

export function GetDatabaseTables() {
  return window['go']['main']['App']['GetDatabaseTables']();
}

export function GetMigrations() {
  return window['go']['main']['App']['GetMigrations']();
}

export function GetUserSettings(arg1) {
  return window['go']['main']['App']['GetUserSettings'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenDatabaseDirectory() {
  return window['go']['main']['App']['OpenDatabaseDirectory']();
}

export function Signup(arg1, arg2, arg3) {
  return window['go']['main']['App']['Signup'](arg1, arg2, arg3);
}

export function UpdateSetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2, arg3, arg4);
}
