// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Login(arg1:string,arg2:string):Promise<models.APIResponse_mooncaketv_services_User_>;

export function Signup(arg1:string,arg2:string,arg3:string):Promise<models.APIResponse_mooncaketv_services_User_>;
