// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteSetting(arg1:number,arg2:number,arg3:boolean):Promise<models.APIResponse_bool_>;

export function GetAllSettings():Promise<models.APIResponse___map_string_interface____>;

export function GetAllUsers():Promise<models.APIResponse___map_string_interface____>;

export function GetCurrentUser(arg1:number):Promise<models.APIResponse_map_string_interface____>;

export function GetDatabaseTables():Promise<models.APIResponse___string_>;

export function GetMigrations():Promise<models.APIResponse___map_string_interface____>;

export function GetUserSettings(arg1:number):Promise<models.APIResponse___map_string_interface____>;

export function Login(arg1:string,arg2:string):Promise<models.APIResponse_mooncaketv_services_User_>;

export function Signup(arg1:string,arg2:string,arg3:string):Promise<models.APIResponse_mooncaketv_services_User_>;

export function UpdateSetting(arg1:number,arg2:string,arg3:number,arg4:boolean):Promise<models.APIResponse_bool_>;
