// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetDatabaseTables() {
  return window['go']['main']['App']['GetDatabaseTables']();
}

export function GetMigrations() {
  return window['go']['main']['App']['GetMigrations']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Signup(arg1, arg2, arg3) {
  return window['go']['main']['App']['Signup'](arg1, arg2, arg3);
}
