// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2);
}

export function DeleteSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSetting'](arg1, arg2, arg3);
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetBookmarkedMediaDetails(arg1) {
  return window['go']['main']['App']['GetBookmarkedMediaDetails'](arg1);
}

export function GetCurrentUser(arg1) {
  return window['go']['main']['App']['GetCurrentUser'](arg1);
}

export function GetDatabaseTables() {
  return window['go']['main']['App']['GetDatabaseTables']();
}

export function GetMigrations() {
  return window['go']['main']['App']['GetMigrations']();
}

export function GetUserBookmarks(arg1) {
  return window['go']['main']['App']['GetUserBookmarks'](arg1);
}

export function GetUserSettings(arg1) {
  return window['go']['main']['App']['GetUserSettings'](arg1);
}

export function IsBookmarked(arg1, arg2) {
  return window['go']['main']['App']['IsBookmarked'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenDatabaseDirectory() {
  return window['go']['main']['App']['OpenDatabaseDirectory']();
}

export function RemoveBookmark(arg1, arg2) {
  return window['go']['main']['App']['RemoveBookmark'](arg1, arg2);
}

export function SaveMediaInfo(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveMediaInfo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function Signup(arg1, arg2, arg3) {
  return window['go']['main']['App']['Signup'](arg1, arg2, arg3);
}

export function UpdateSetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2, arg3, arg4);
}
